### ISSUE TITLE
lowercase i has priority

### ISSUE THREAD

**Issue by noamhacker** [Decagon/star.js#6]
attempt 1:
"i forgot to a word here" + "write*" = "write forgot to a word here"

attempt 2:
"I forgot to a word here" + "write*" = "I forgot write a word here"
(note it replaced "to" with "write")

**Comment by alexyorke** [comment]
Good find! It seems like there's an issue with how the levenshtein algorithm is implemented, and it adds a cost to replacing letters in different cases.

In the meantime, we can make Star.js return false on errors like these, since this is a bit too complex of a correction right now as there is no anchor point to put the word in. I've added it to the 2.0 milestone because I think this would be an excellent example for Star.js in the 2.x series, as we get the code cleaned up so that we can start adding these smarter cases.

**Comment by noamhacker** [comment]
Glad I could help! Nice job with this so far
